--                                         RETAILS SALES ANALYSIS


select * from customer limit 5;

-- REvenue Generated by both male and Female

select "Gender", sum(purchase_amount) as revenue  
from customer
group by "Gender";

-- Used discount still purchase amount greater than avg purchase amount

select "Customer ID",purchase_amount
from customer
where "Discount Applied" = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer);

-- Top 5 products with highest avg review rating

SELECT  "Item Purchased",ROUND(AVG("Review Rating")::numeric, 2) AS rating
FROM customer
GROUP BY "Item Purchased"
ORDER BY rating DESC
LIMIT 5;

-- compared avg purchase amount between standard and express shiping

select "Shipping Type",
round(avg(purchase_amount),2)
from customer
where "Shipping Type" in ('Standard', 'Express')
group by "Shipping Type";

--  Compared average spend and total revenue -between subscribers and non-subscribers.

select "Subscription Status",
count("Customer ID") as total_customer,
round(avg(purchase_amount),2) as avg_spent,
round(sum(purchase_amount),2) as total_spent
from customer
group by "Subscription Status"
order by avg_spent,total_spent desc;

-- 5 products with the highest percentage of purchases with discounts applied 

select "Item Purchased",
round(sum(case when "Discount Applied" = 'Yes' then 1 else 0 End)* 100.0 / count(*) ,2) as discount_rate
from customer
group by "Item Purchased"
order by discount_rate desc
limit 5;

-- Segmented customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and count of each segment. 

with customer_type as (
SELECT "Customer ID", "Previous Purchases",
CASE 
    WHEN "Previous Purchases" = 1 THEN 'New'
    WHEN "Previous Purchases" BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

-- Top 3 most purchased products within each category

WITH item_counts AS (
    SELECT "Category",
           "Item Purchased",
           COUNT("Customer ID") AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY "Category" ORDER BY COUNT("Customer ID") DESC) AS item_rank
    FROM customer
    GROUP BY "Category", "Item Purchased"
)
SELECT item_rank,"Category", "Item Purchased", total_orders
FROM item_counts
WHERE item_rank <=3;
 
--  Customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe

SELECT "Subscription Status",
       COUNT("Customer ID") AS repeat_buyers
FROM customer
WHERE "Previous Purchases" > 5
GROUP BY "Subscription Status";


-- Revenue contribution of each age group

SELECT 
    "Age",
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY "Age"
ORDER BY total_revenue desc;





